name: My First Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, DevOps World!"

      - name: Simulate Work
        run: echo "Running some checks..."

      - name: Create a file
        run: echo "This is my first DevOps artifact" > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-first-artifact
          path: output.txt
