name: My First Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, DevOps World!"

      - name: Break the pipeline
        run: invalid_command_123"
